apiVersion: v1
kind: Service
metadata:
  name: bucardo-machine
  labels:
    app: bucardo-machine
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgresql
  selector:
    app: bucardo-machine
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bucardo-machine
  namespace: bucardo-machine
spec:
  serviceName: bucardo-machine
  replicas: 1
  selector:
    matchLabels:
      app: bucardo-machine
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bucardo-machine
    spec:
      volumes:
      - name: pgpass
        secret:
          secretName: pgpass
          defaultMode: 0600
          items:
            - key: pgpass
              path: .pgpass
      initContainers:
      - name: bucardo-init
        image: datica/bucardo_machine:latest
        imagePullPolicy: Always
        command: ['bash', '-c', '/scripts/init.sh']
        volumeMounts:
        - name: bucardo-data
          mountPath: /var/lib/postgresql
        resources: {}
      containers:
      - name: bucardo
        image: datica/bucardo_machine:latest
        imagePullPolicy: IfNotPresent
        command: ['bash', '-c', '/scripts/bucardo.sh']
        volumeMounts:
        - name: bucardo-data
          mountPath: /var/lib/postgresql
        - name: pgpass
          mountPath: /root
          readOnly: true
        resources: {}
  volumeClaimTemplates:
  - metadata:
      name: bucardo-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: persistent-storage
      resources:
        requests:
          storage: 10Gi
