apiVersion: v1
kind: Service
metadata:
  name: utility-box
  labels:
    app: utility-box
spec:
  clusterIP: None
  ports:
  - port: 65000
    name: dummy-port
  selector:
    app: utility-box
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: utility-box
  namespace: utility-box
spec:
  serviceName: utility-box
  replicas: 1
  selector:
    matchLabels:
      app: utility-box
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: utility-box
    spec:
      volumes:
      - name: utility-secrets
        secret:
          secretName: utility-secrets
      containers:
      - name: utility
        image: datica/bucardo_machine:latest
        imagePullPolicy: Always
        command: ['/sbin/init']
        volumeMounts:
        - name: utility-data
          mountPath: /util
        - name: utility-secrets
          mountPath: /root/secrets
          readOnly: true
        resources: {}
  volumeClaimTemplates:
  - metadata:
      name: utility-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: persistent-storage
      resources:
        requests:
          storage: 10Gi
